  type Query {
    getUsers: [User]
    getUser(id: String): User
  }
  type Mutation {
    createUser(
      nombre: String
      apellidoPaterno: String
      apellidoMaterno: String
      telefono: String
      direccion: DireccionInput
    ): User
    updateUser(
      id: String
      nombre: String
      apellidoPaterno: String
      apellidoMaterno: String
      telefono: String
      direccion: DireccionInput
    ): User
    deleteUser(id: String): String
  }

    type Direccion {
    calle: String
    numero: String
    estado: String
    ciudad: String
  }
  input DireccionInput {
    calle: String
    numero: String
    estado: String
    ciudad: String
  }
    type User {
    id: String
    nombre: String
    apellidoPaterno: String
    apellidoMaterno: String
    telefono: String
    direccion: Direccion
  }